# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 110, 391, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.login_edit.setObjectName("login_edit")
        self.verticalLayout.addWidget(self.login_edit)
        self.pass_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pass_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_edit.setObjectName("pass_edit")
        self.verticalLayout.addWidget(self.pass_edit)
        self.check_show_pass = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_show_pass.setObjectName("check_show_pass")
        self.verticalLayout.addWidget(self.check_show_pass)
        self.auth_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.auth_btn.setObjectName("auth_btn")
        self.verticalLayout.addWidget(self.auth_btn)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 30, 241, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 22))
        self.menubar.setObjectName("menubar")
        self.menuHello = QtWidgets.QMenu(self.menubar)
        self.menuHello.setObjectName("menuHello")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHello.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_edit.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.pass_edit.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.check_show_pass.setText(_translate("MainWindow", "Показать пароль"))
        self.auth_btn.setText(_translate("MainWindow", "Войти"))
        self.label.setText(_translate("MainWindow", "Точка проката ЦПКиО им. Маяковского"))
        self.menuHello.setTitle(_translate("MainWindow", "Hello"))
